debug = true
players = 200
language = 'de'
host = '0.0.0.0'
port = 7788
modules = [ 'js-module', 'csharp-module' ]
resources = ['*']

[csharp-module]
disableDependencyDownload = true

[js-module]
heap-profiler = true
profiler = true
extra-cli-args = ["--inspect=127.0.0.1:9229", "--max-old-space-size=8192"]

# Enable node.js inspector
[js-module.inspector]
host = "127.0.0.1"
port = 9229

[voice]
# The bitrate of the voice server
bitrate = 64000
# The secret for the external server (only needed when using externalHost)
# The secret must consist of numeric values only
# The external host address (leave 127.0.0.1, if voice-server is on same machine)
externalHost = "127.0.0.1"
# The external host port
externalPort = 7798
# The external host public address (should be the ip address of your server, not localhost!)
externalPublicHost = "0.0.0.0"
# The external host public port
externalPublicPort = 7799